export const FETCH_USER = "FETCH_USER";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const UPDATE_USER = "UPDATE_USER";



export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const FETCH_PATIENT_NAMES = "FETCH_PATIENT_NAMES";
export const ADD_PATIENT = "ADD_PATIENT";
export const ADD_TREATMENT = "ADD_TREATMENT";
export const DELETE_PATIENT_TREATMENT = "DELETE_PATIENT_TREATMENT";
export const UPDATE_PATIENT_TREATMENT = "UPDATE_PATIENT_TREATMENT";




